### ISSUE TITLE
Trouble instaling libcidr-ffi

### ISSUE THREAD

**Issue by andralungu** [GUI/lua-libcidr-ffi#3]
```sudo luarocks install libcidr-ffi  
Warning: falling back to curl - install luasec to get native HTTPS support
Installing https://luarocks.org/libcidr-ffi-0.1.2-1.src.rock

Error: Could not find library file for CIDR
  No file libcidr.a in /usr/local/lib
  No file libcidr.dylib in /usr/local/lib
  No file matching libcidr.so.* in /usr/local/lib
  No file libcidr.a in /usr/lib
  No file libcidr.dylib in /usr/lib
  No file matching libcidr.so.* in /usr/lib
You may have to install CIDR in your system and/or pass CIDR_DIR or CIDR_LIBDIR to the luarocks command.
Example: luarocks install libcidr-ffi CIDR_DIR=/usr/local```

Could you please also mention the prerequisites in the README?

**Comment by GUI** [comment]
@andralungu: Apologies for the very belated response. You'll need to have libcidr installed on your system prior to installation. I've attempted to update the README to provide more detailed instructions on how to install libcidr as part the [installation steps](https://github.com/GUI/lua-libcidr-ffi#installation). I've also added more [troubleshooting](https://github.com/GUI/lua-libcidr-ffi#troubleshooting) details if you run into issues after libcidr is installed. Hopefully those README updates will better explain things, so I'm going to close this issue, but definitely reach out if you're still running into any issues. Thanks for brining this up!
